In [31]:
from numpy import random

x = random.randint(100, 200)
x

114

In [67]:
x = random.rand()
x

0.328451270881682

In [53]:
x = random.randint(100, size=(5))
x

array([69, 71, 45, 54, 90])

In [56]:
x = random.randint(100, size=(3, 4))
x

array([[57, 59, 31, 54],
       [95, 88, 93, 11],
       [78, 55, 15,  4]])

In [69]:
x = random.rand(3, 2)
x

array([[0.5179062 , 0.56767467],
       [0.23903561, 0.36413915],
       [0.63240042, 0.09470872]])

In [76]:
x = random.choice([3, 5, 2, 9, 0])
x

5

In [77]:
x = random.choice([3, 5, 2, 9, 0], size=(2, 3))
x

array([[2, 2, 2],
       [0, 9, 2]])