In [1]:
import numpy as np

a = np.array([4, 5, 6, 2, 7, 1, 9, 3])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [2]:
b = np. array(['Nachiket', 'Chaitanya', 'Aditi', 'Prajakta', 'Padmaja', 'Rohit'])
np.sort(b)

array(['Aditi', 'Chaitanya', 'Nachiket', 'Padmaja', 'Prajakta', 'Rohit'],
      dtype='<U9')

In [3]:
c = np.array([True, False, True])
np.sort(c)

array([False,  True,  True])

In [4]:
d = np.array([[5, 2, 1], [9, 5, 7], [6, 1, 9]])
np.sort(d)

array([[1, 2, 5],
       [5, 7, 9],
       [1, 6, 9]])